package com.example.studentapp.service.impl;

import com.example.studentapp.model.Course;
import com.example.studentapp.repository.CourseRepository;
import com.example.studentapp.repository.RegistrationRepository;
import com.example.studentapp.service.CourseService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

/**
 * CourseServiceImpl
 * Implementation of Course Management Business Logic.
 * Now includes cascading deletes for registrations for deleted courses.
 */
@Service
public class CourseServiceImpl implements CourseService {

    // core persistence logic handled by the CourseRepository interface
    private final CourseRepository courseRepository;
    // Registration linkage logic handled by the RegistrationRepository
    private final RegistrationRepository registrationRepository;

    // constructor-based Injection: Wiring in all necessary repository controllers
    @Autowired
    public CourseServiceImpl(CourseRepository courseRepository, RegistrationRepository registrationRepository) {
        this.courseRepository = courseRepository;
        this.registrationRepository = registrationRepository;
    }

    /**
     * getAllCourses: returns the complete academic catalog
     * @return catalog list from the course table
     */
    @Override
    public List<Course> getAllCourses() {
        // Query Logic: Fetch all defined course modules from the database
        return courseRepository.findAll();
    }

    /**
     * getCourseById: Retrieves a specific course definition
     * @param id - academic module unique ID
     * @return found course or null
     */
    @Override
    public Course getCourseById(Long id) {
        // Lookup Logic: unique search by Primary Key auto-generated by JPA
        return courseRepository.findById(id).orElse(null);
    }

    /**
     * saveCourse: Logic for adding a new module or updating an existing one
     * @param course - module details to save
     * @return the saved course entry
     */
    @Override
    public Course saveCourse(Course course) {
        // catalog Management: ensures course is in the persistent database registry
        return courseRepository.save(course);
    }

    /**
     * deleteCourse: logic for removing a retired course and its data
     * @param id - unique module ID to remove
     */
    @Override
    @Transactional
    public void deleteCourse(Long id) {
        // Step 1: Cleanup: Ensure no registrations exist for the retired module
        // Prevents data integrity errors on the main registration list
        registrationRepository.deleteByCourseId(id);
        // Step 2: Removal: Final removal from the catalog spec table
        courseRepository.deleteById(id);
    }

    /**
     * countCourses: returns the total number of catalog modules
     */
    @Override
    public long countCourses() {
        // Registry Stat: Query the row count of academic modules
        return courseRepository.count();
    }
}
